# ──────────────────────────────────────────────────────────────────
# OrbitDesk ConfigMap — Non-sensitive configuration
# ──────────────────────────────────────────────────────────────────
apiVersion: v1
kind: ConfigMap
metadata:
  name: orbitdesk-config
  namespace: orbitdesk
  labels:
    app.kubernetes.io/part-of: orbitdesk
data:
  # ── General ────────────────────────────────────────────────────
  NODE_ENV: "production"

  # ── Backend ────────────────────────────────────────────────────
  BACKEND_PORT: "5000"
  MONGODB_URI: "mongodb://mongodb-svc:27017/OrbitDesk"
  KAFKA_BROKER: "kafka-svc:9092"

  # ── Notification Service ───────────────────────────────────────
  NOTIFICATION_PORT: "3001"
  KAFKA_BROKERS: "kafka-svc:9092"
  NOTIFICATION_MONGODB_URI: "mongodb://mongodb-svc:27017/OrbitDesk_Notifications"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"

  # ── Kafka ──────────────────────────────────────────────────────
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-svc:2181"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"

  # ── Zookeeper ──────────────────────────────────────────────────
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
